=== cristianbanto/test-war/target/currencyconverter/WEB-INF/classes/xsd/DataFeedSources.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://finestmedia.ee/currencyconverter/generated" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="DataFeedSources">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="DataFeedSource" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="id"/>
              <xs:element type="xs:string" name="displayName"/>
              <xs:element type="xs:boolean" name="enabled"/>
              <xs:element type="xs:string" name="url"/>
              <xs:element type="xs:string" name="dateFormat" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cristianbanto/test-war/target/classes/dataFeedSources.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataFeedSources xmlns="http://finestmedia.ee/currencyconverter/generated"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://finestmedia.ee/currencyconverter/generated xsd/DataFeedSources.xsd">
	<DataFeedSource>
		<id>eestipank</id>
		<displayName>Eesti Pank</displayName>
		<enabled>true</enabled>
		<url>http://statistika.eestipank.ee/Reports?type=curd&amp;format=xml&amp;lng=est&amp;print=off&amp;date1=</url>
		<dateFormat>YYYY-MM-dd</dateFormat>
	</DataFeedSource>
	<DataFeedSource>
		<id>leedupank</id>
		<displayName>Leedu Pank</displayName>
		<enabled>true</enabled>
		<url>http://webservices.lb.lt/ExchangeRates/ExchangeRates.asmx/getExchangeRatesByDate?Date=</url>
		<dateFormat>YYYY-MM-dd</dateFormat>
	</DataFeedSource>
</DataFeedSources>
